【发现已存在的游戏窗口】
【现在处于主菜单】
【目标出现】images/battery.png 置信度是：0.9999996423721313
Using CPU. Note: This module is much faster with a GPU.
当前电量为：178 
任务开始，执行 1 次循环
【现在处于主菜单】
【1】等待目标中 images/lobby.png
【2】等待目标中 images/lobby.png
【3】等待目标中 images/lobby.png
【4】等待目标中 images/lobby.png
【5】等待目标中 images/lobby.png
【6】等待目标中 images/lobby.png
【7】等待目标中 images/lobby.png
【8】等待目标中 images/lobby.png
【9】等待目标中 images/lobby.png
【10】等待目标中 images/lobby.png
【11】等待目标中 images/lobby.png
【12】等待目标中 images/lobby.png
【13】等待目标中 images/lobby.png
【14】等待目标中 images/lobby.png
【15】等待目标中 images/lobby.png
【16】等待目标中 images/lobby.png
【17】等待目标中 images/lobby.png
【18】等待目标中 images/lobby.png
【19】等待目标中 images/lobby.png
【20】等待目标中 images/lobby.png
--------等待超时,开始重试--------
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 742, in run
    battery=battery_check()    #获取体力信息
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 248, in battery_check
    menu('stay')
    ~~~~^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 194, in menu
    time.sleep(wait_speed)
    ~~~~~~~~~~^^^^^^^^^^^^
KeyboardInterrupt

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 742, in run
    battery=battery_check()    #获取体力信息
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 248, in battery_check
    menu('stay')
    ~~~~^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 194, in menu
    time.sleep(wait_speed)
    ~~~~~~~~~~^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 773, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 770, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
