【发现已存在的游戏窗口】
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
正在返回菜单,请保持游戏画面处于前台
【现在处于主菜单】
【目标出现】images/lobby.png 置信度是：0.9999196529388428
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 684, in run
    coffee()
    ~~~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 355, in coffee
    click('old_map.png')
    ~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 74, in click
    match_tpl(tpl,'click',skip=skip)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 29, in match_tpl
    template = cv2.imread(tpl)  # 读取模板
  File "C:\Python\Lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'old_map.png'

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 684, in run
    coffee()
    ~~~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 355, in coffee
    click('old_map.png')
    ~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 74, in click
    match_tpl(tpl,'click',skip=skip)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 29, in match_tpl
    template = cv2.imread(tpl)  # 读取模板
  File "C:\Python\Lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'old_map.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 710, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 707, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
KeyboardInterrupt
