【发现已存在的游戏窗口】
【现在处于主菜单】
【目标出现】images/battery.png 置信度是：0.9999998211860657
None
Using CPU. Note: This module is much faster with a GPU.
当前电量为：231 
任务开始，执行 3 次循环
【现在处于主菜单】
【1】等待目标中 images/lobby.png
【目标出现】images/lobby.png 置信度是：0.9999196529388428
【1】等待目标中 images/tactics.png
【2】等待目标中 images/tactics.png
【3】等待目标中 images/tactics.png
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 733, in run
    TASK()
    ~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 687, in <lambda>
    TASK=lambda :hunt(task_list[task_index])
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 491, in hunt
    click('images/tactics.png')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 77, in click
    match_tpl(tpl,'click',skip=skip)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 75, in match_tpl
    time.sleep(wait_speed)
    ~~~~~~~~~~^^^^^^^^^^^^
KeyboardInterrupt

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 733, in run
    TASK()
    ~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 687, in <lambda>
    TASK=lambda :hunt(task_list[task_index])
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 491, in hunt
    click('images/tactics.png')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 77, in click
    match_tpl(tpl,'click',skip=skip)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 75, in match_tpl
    time.sleep(wait_speed)
    ~~~~~~~~~~^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 754, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 751, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
