¡¾·¢ÏÖÒÑ´æÔÚµÄÓÎÏ·´°¿Ú¡¿
ÕıÔÚ·µ»Ø²Ëµ¥,Çë±£³ÖÓÎÏ·»­Ãæ´¦ÓÚÇ°Ì¨
¡¾ÏÖÔÚ´¦ÓÚÖ÷²Ëµ¥¡¿
¡¾Ä¿±ê³öÏÖ¡¿images/battery.png ÖÃĞÅ¶ÈÊÇ£º1.0
Using CPU. Note: This module is much faster with a GPU.
[32m¡¾Ê£ÓàµçÁ¿:100¡¿[0m
---------ÈÎÎñ½áÊø-----------
¡¾ÓÎÏ·ÔÚ10Ãëºó¹Ø±Õ¡¿
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 761, in run
    shutdown()
    ~~~~~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 316, in shutdown
    time.sleep(10)
    ~~~~~~~~~~^^^^
KeyboardInterrupt

Exception:Ö÷Ïß³Ì³ö´í
°´»Ø³µ¼üÍË³ö(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 761, in run
    shutdown()
    ~~~~~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 316, in shutdown
    time.sleep(10)
    ~~~~~~~~~~^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 768, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 765, in run
    input('Exception:Ö÷Ïß³Ì³ö´í\n°´»Ø³µ¼üÍË³ö(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
