【发现已存在的游戏窗口】
【现在处于主菜单】
【目标出现】images/battery.png （置信度：0.9999998211860657）
Using CPU. Note: This module is much faster with a GPU.
当前电量为：195 
任务开始，执行 1 次循环
【现在处于主菜单】
【目标出现】images/lobby.png （置信度：0.9999196529388428）
【目标出现】images/tactics.png （置信度：0.9765910506248474）
【目标出现】images/train.png （置信度：0.9761336445808411）
【等待目标中】 images/go.png [1]
【等待目标中】 images/go.png [2]
【等待目标中】 images/go.png [3]
【等待目标中】 images/go.png [4]
【等待目标中】 images/go.png [5]
【等待目标中】 images/go.png [6]
【等待目标中】 images/go.png [7]
【等待目标中】 images/go.png [8]
【等待目标中】 images/go.png [9]
【等待目标中】 images/go.png [10]
【等待目标中】 images/go.png [11]
【等待目标中】 images/go.png [12]
【等待目标中】 images/go.png [13]
【等待目标中】 images/go.png [14]
【等待目标中】 images/go.png [15]
【等待目标中】 images/go.png [16]
【等待目标中】 images/go.png [17]
【等待目标中】 images/go.png [18]
【等待目标中】 images/go.png [19]
【等待目标中】 images/go.png [20]
--------等待超时,开始重试--------
【正在返回菜单】请保持游戏画面处于前台
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 737, in run
    battery=battery_check()    #获取体力信息
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 244, in battery_check
    menu('stay')
    ~~~~^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 192, in menu
    time.sleep(wait_speed)
    ~~~~~~~~~~^^^^^^^^^^^^
KeyboardInterrupt

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 737, in run
    battery=battery_check()    #获取体力信息
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 244, in battery_check
    menu('stay')
    ~~~~^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 192, in menu
    time.sleep(wait_speed)
    ~~~~~~~~~~^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 767, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 764, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
