【发现已存在的游戏窗口】
【现在处于主菜单】
[TGT]images/battery.png confident：1.0
Using CPU. Note: This module is much faster with a GPU.
当前电量为：180 
任务开始，执行 1 次循环
正在返回主菜单[1]正在返回主菜单[2]正在返回主菜单[3]正在返回主菜单[4]正在返回主菜单[5]正在返回主菜单[6]正在返回主菜单[7]正在返回主菜单[8]正在返回主菜单[9]正在返回主菜单[10]正在返回主菜单[11]正在返回主菜单[12]正在返回主菜单[13]正在返回主菜单[14]正在返回主菜单[15]正在返回主菜单[16]正在返回主菜单[17]正在返回主菜单[18]正在返回主菜单[19]正在返回主菜单[20]正在返回主菜单[21]正在返回主菜单[22]正在返回主菜单[23]正在返回主菜单[24]正在返回主菜单[25]正在返回主菜单[26]正在返回主菜单[27]正在返回主菜单[28]正在返回主菜单[29]正在返回主菜单[30]正在返回主菜单[31]正在返回主菜单[32]正在返回主菜单[33]正在返回主菜单[34]正在返回主菜单[35]正在返回主菜单[36]正在返回主菜单[37]正在返回主菜单[38]正在返回主菜单[39]正在返回主菜单[40]正在返回主菜单[41]正在返回主菜单[42]正在返回主菜单[43]正在返回主菜单[44]正在返回主菜单[45]正在返回主菜单[46]正在返回主菜单[47]正在返回主菜单[48]正在返回主菜单[49]正在返回主菜单[50]-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 748, in run
    TASK()
    ~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 689, in <lambda>
    TASK=lambda :upgrade(task_list[task_index])
                 ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 521, in upgrade
    menu('leave')
    ~~~~^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 196, in menu
    pydirectinput.press('esc', )
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 242, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 544, in press
    downed = keyDown(k)
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 243, in wrapper
    _handlePause(funcArgs.get("_pause"))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 232, in _handlePause
    time.sleep(PAUSE)
    ~~~~~~~~~~^^^^^^^
KeyboardInterrupt

Exception:主线程出错
按回车键退出(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 748, in run
    TASK()
    ~~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 689, in <lambda>
    TASK=lambda :upgrade(task_list[task_index])
                 ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 521, in upgrade
    menu('leave')
    ~~~~^^^^^^^^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 196, in menu
    pydirectinput.press('esc', )
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 242, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 544, in press
    downed = keyDown(k)
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 243, in wrapper
    _handlePause(funcArgs.get("_pause"))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pydirectinput\__init__.py", line 232, in _handlePause
    time.sleep(PAUSE)
    ~~~~~~~~~~^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 774, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 771, in run
    input('Exception:主线程出错\n按回车键退出(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
